# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: istio-system
  labels:
    helm.sh/chart: grafana-8.0.0  # Update with the correct chart version
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "8.0.0"  # Update with the Grafana version
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 3000
      protocol: TCP
      targetPort: 3000
  externalIPs:
    - 139.177.184.147
    - 139.162.15.60
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
